global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'usuarios'
    static_configs:
      - targets: ['usuarios:3001']

  - job_name: 'restaurantes'
    static_configs:
      - targets: ['restaurantes:3002']

  - job_name: 'pedidos'
    static_configs:
      - targets: ['pedidos:3003']

  - job_name: 'pagos'
    static_configs:
      - targets: ['pagos:3004']

  - job_name: 'repartidores'
    static_configs:
      - targets: ['repartidores:3005']

  - job_name: 'notificaciones'
    static_configs:
      - targets: ['notificaciones:3006']
